### ISSUE TITLE
有关我的创建一个开发分支的想法

### ISSUE THREAD

**Issue by Guanrenfu** [Guanrenfu/Linux-quick-install-or-config#2]
@veners1995 
表示我刚刚发现这次的版本特别稳定。而我刚刚作了很多的修改（最大的修改就是增加了窗口管理器），但是由于没有测试所以肯定有bug。因此我想单独创建一个项目作为本项目的开发分支，我们将所有的更改首先推送到那个项目，然后测试没有bug后再在本项目重新推送一遍。

这是我更改后的代码：http://paste.ubuntu.com/11923887/

**Comment by veners1995** [comment]
无此必要，你可以创建一个release文件夹，将稳定版本的脚本放在里面；
或者创建一个分支用于release稳定版本的代码，可以参考bcloud的模式．

**Comment by Guanrenfu** [comment]
@veners1995 明白了，那么我就创建一个release文件夹，然后在README中标注一下。
